import { User } from './../../../models/user';
import { Beneficiary } from './../../../models/beneficiary';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-beneficiary-app',
  templateUrl: './beneficiary-app.component.html',
  styleUrls: ['./beneficiary-app.component.css']
})
export class BeneficiaryAppComponent implements OnInit {
  user: User;
  showBeneficiaryDetailForm = false;

  constructor() { }

  ngOnInit() {
      this.user = {
      id: 1,
      email: 'email@example.com',
      firstName: 'Bob',
      lastName: 'Ross',
      primaryBeneficiaries: [
        {
        id: 1,
        firstName: 'Bruce',
        lastName: 'Wayne',
        percentOfBenefit: 50
      },
      {
        id: 2,
        firstName: 'John',
        lastName: 'Wayne',
        percentOfBenefit: 50
      }
    ],
      contingentBeneficiaries: []
    };
  }

  /************************************************************
   * Only for testing. Should be removed when no longer needed
   * Automatically generates an id for a Beneficiary
   * Simualtes what a database would do for ids
  ************************************************************/
  genId(beneficiaries: Beneficiary[]): number {
    return beneficiaries.length > 0 ? Math.max(...beneficiaries.map(beneficiary => beneficiary.id)) + 1 : 1;
  }

  toggleShowBeneficiaryDetailForm() {
    this.showBeneficiaryDetailForm = !this.showBeneficiaryDetailForm;
  }

  deleteBeneficiary(beneficiary: Beneficiary) {
    this.user.primaryBeneficiaries = this.user.primaryBeneficiaries.filter(b => b.id !== beneficiary.id);

    this.adjustBeneficiaryPercent();
  }

  addBeneficiary(beneficiary: Beneficiary) {
    this.showBeneficiaryDetailForm = false;
    this.user.primaryBeneficiaries.push(beneficiary);

    const lastIndex = this.user.primaryBeneficiaries.length - 1;

    /********************************************
     * This would need to be replaced with the id
     * of the object returning from the database
     * after if has been inserted and an id has
     * been auto-generated by the database
     ********************************************/
    const newId = this.genId(this.user.primaryBeneficiaries);
    this.user.primaryBeneficiaries[lastIndex].id = newId;

    this.adjustBeneficiaryPercent(this.user.primaryBeneficiaries[lastIndex]);
  }

  closeBeneficiaryDetailForm() {
    this.showBeneficiaryDetailForm = false;
  }

  // Automatically adjust the beneficiary percent
  adjustBeneficiaryPercent(beneficiary?: Beneficiary) {
    // Only 1 beneficiary, so default to 100%
    if (this.user.primaryBeneficiaries.length === 1) {
      this.user.primaryBeneficiaries[0].percentOfBenefit = 100;
    }

    // More than 2 beneficiaries
    if (this.user.primaryBeneficiaries.length > 1) {
      const totalBeneficiaryAmount = 100;

      // When the user deletes the number of beneficiaries
      // Evenly adjust the beneficiaries
      if (beneficiary === undefined || beneficiary === null) {
        const numberOfBeneficiaries = this.user.primaryBeneficiaries.length;

        for (let i = 0; i < numberOfBeneficiaries; i++) {
          const dividedAmount = Math.floor(totalBeneficiaryAmount / numberOfBeneficiaries);
          this.user.primaryBeneficiaries[i].percentOfBenefit = dividedAmount;
        }

        // Any remaing amount, add it to the first beneficiary
        const remainingAmount = Math.floor(totalBeneficiaryAmount % numberOfBeneficiaries);
        this.user.primaryBeneficiaries[0].percentOfBenefit += remainingAmount;

        // When the user adds the number of beneficiaries
        // Evenly adjust the beneficiaries based on the
        // difference in the user's last adjusted beneficiary percent
      } else {
        const newTotalBeneficiaryAmount = totalBeneficiaryAmount - beneficiary.percentOfBenefit;
        const otherBeneficiaries = this.user.primaryBeneficiaries.filter(b => b.id !== beneficiary.id);
        const numberOfBeneficiaries = otherBeneficiaries.length;

        for (let i = 0; i < numberOfBeneficiaries; i++) {
          const dividedAmount = Math.floor(newTotalBeneficiaryAmount / numberOfBeneficiaries);
          otherBeneficiaries[i].percentOfBenefit = dividedAmount;
        }

        // Any remaing amount, add it to the first beneficiary
        const remainingAmount = Math.floor(newTotalBeneficiaryAmount % (otherBeneficiaries.length));
        otherBeneficiaries[0].percentOfBenefit += remainingAmount;
      }
    }
  }

}
